name: webthings-gateway
version: 1.0.0
summary: WebThings Gateway
description: Directly monitor and control your home over the web.

base: core18
grade: devel
confinement: devmode

apps:
  webthings-gateway:
    command: cd $SNAP/opt/webthings-gateway && node build/gateway.js
    environment:
      PYTHONPATH: $SNAP/opt/webthings-gateway/python

parts:
  webthings-gateway:
    source: https://github.com/WebThingsIO/gateway.git
    source-type: git
    source-tag: 1.0.0
    plugin: better-nodejs
    nodejs-package-manager: npm
    nodejs-version: 10.23.0
    build-packages:
      - autoconf
      - automake
      - build-essential
      - git
      - libtool
      - pkg-config
      - python
      - python3
      - python3-pip
      - python3-setuptools
    stage-packages:
      - arping
      - ffmpeg
      - iputils-ping
      - libcap2-bin
      - lsb-release
      - mosquitto
      - net-tools
      - python
      - python-six
      - python3
    override-build: |
      # Add the locally installed npm to our path.
      # export makes it also propagate into the sub-shell.
      export PATH=$PATH:$(pwd)/../npm/bin

      # Allow npm to run as root properly
      # https://docs.npmjs.com/misc/config#unsafe-perm
      npm config -g set unsafe-perm true

      # Install node-gyp, as it didn't seem to get installed by `npm install`
      # for some reason
      npm install -g node-gyp

      # Start a sub-shell so that the SUDO_* bits aren't propagated to the rest
      # of the process unnecessarily.
      (
        # Make the subshell exit if one of the commands fails
        set -e

        # Unset the sudo environment variables to make git happy
        # https://github.com/snapcore/snapcraft/commit/93fd2825733ea8725502d2ab62124be5179c6407
        unset SUDO_UID
        unset SUDO_GID

        # Install all of the necessary node modules
        CPPFLAGS="-DPNG_ARM_NEON_OPT=0" npm ci

        # Run the webpack process now, rather than at each launch
        ./node_modules/.bin/webpack

        # Clean up a couple things
        rm -rf ./node_modules/gifsicle
        rm -rf ./node_modules/mozjpeg

        # Remove all but production dependencies
        npm prune --production
      )

      # Install Python library
      python3 -m pip install --system --install-option="--prefix=" --no-binary=:all: -r ./requirements.txt

      # Install things into the snap
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt
      cp -r . $SNAPCRAFT_PART_INSTALL/opt/webthings-gateway
      rm -rf $SNAPCRAFT_PART_INSTALL/opt/webthings-gateway/.git
